from tkinter import *

foablak =Tk()
foablak.title('Étrend')
foablak.minsize(width =800,height=800)
txt1=Label(foablak,text='Mi a célja az étrendel?')
txt2=Label(foablak,text='Étrend')
txt3=Label(foablak,text='Az általunk össze állított étrend tömegnöveléshez (60-70kg-ig).')

jelolo1 =Checkbutton(foablak,text='Tömegnövelés',)
jelolo2 =Checkbutton(foablak,text='Diéta',)
jelolo3 =Checkbutton(foablak,text='Csirkemell,rizs(2700kalória/nap)')
jelolo4 =Checkbutton(foablak,text='Tejszines csirke, tésztával(2700 kalória/nap)',)
jelolo6 =Checkbutton(foablak,text='Rántott sertés comb, salátával+bármilyen körettel(2700 kalória/nap)',)
jelolo7 =Checkbutton(foablak,text='pulyka mell+krumpli+zöldség (2700kalória/nap)',)
jelolo8 =Checkbutton(foablak,text='Bolognai(2700 kalória/nap)',)
jelolo1.grid(row=3,sticky=W,)
jelolo2.grid(row=4,sticky=W)
jelolo3.grid(row=6,sticky=W,pady=10,columnspan=20)
jelolo4.grid(row=7,sticky=W,pady=10)
jelolo6.grid(row=9,sticky=W,pady=10)
jelolo7.grid(row=10,sticky=W,pady=10)
jelolo8.grid(row=11,sticky=W,pady=10)
txt1.grid(row=2,sticky=W,)
txt2.grid(row=0,sticky=W,column=4)
txt3.grid(row=5,sticky=E,)

jelolo9 =Checkbutton(foablak,text='Csirkemell, rizs+saláta 1600kalória/nap')
jelolo10 =Checkbutton(foablak,text='Tejszines csirke, tésztával(1600 kalória/nap)',)
jelolo11 =Checkbutton(foablak,text='Tésztasaláta(1600kalória/nap)',)
jelolo12 =Checkbutton(foablak,text=' pulyka mell+zöldség (1600kalória/nap)',)
jelolo13 =Checkbutton(foablak,text='Cézár saláta(1600 kalória/nap)',)
jelolo9.grid(row=12,sticky=W,pady=10,columnspan=20)
jelolo10.grid(row=13,sticky=W,pady=10)
jelolo11.grid(row=14,sticky=W,pady=10)
jelolo12.grid(row=15,sticky=W,pady=10)
jelolo13.grid(row=16,sticky=W,pady=10)



foablak.mainloop()